name: TestPlugin
version: ${project.version}
main: me.b0bbydev.testplugin.TestPluginMain
api-version: 1.16
authors: [b0bbydev]
description: First plugin
commands:
  fly:
    usage: /fly <player>
    description: This command allows you to toggle a players flight.

  godModeOn:
    usage: /godModeOn
    description: This command allows you to toggle godmode on.

  godModeOff:
    usage: /godModeOff
    description: This command allows you to toggle godmode off.

  fullFood:
    usage: /fullFood
    description: This command will fill the players hunger bar.

  kill:
    usage: /kill <target>
    description: This command allows you to kill yourself or another player.

  tp:
    usage: /tp <otherplayer> , /tp <player> <otherplayer>
    description: This command will allow player to teleport to each other.

  tpbow:
    usage: /tpbow
    description: Spawn a teleport bow.

  fullHealth:
    usage: /fullHealth
    description: This command will fill the players health to full.

  oneKOSword:
    usage: /oneKOSword
    description: This command gives the player a one-hit sword.

  armorStand:
    usage: /armorStand
    description: This command will spawn a armorStand GUI.